### ISSUE TITLE
permission to your GitHub repo

### ISSUE THREAD

**Issue by zhuyijie25** [QMSS-GR5069-Spring-2022/gr5069-homework-2-elliotttrio#2]
Hi Elliot,

I am wondering whether you have added me to your GitHub repo's collaborator? I just want to sent a pull request but the access to your repo was denied.

**Comment by elliotttrio** [comment]
Hi Jackie,

You are not assigned as my collaborator for this project. We do not have the same collaborator/owners for this project. I would look at the list again.
